server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8199/eureka/
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/api/**
          filters:
            - AuthFilter
        - id: microservice-travel
          uri: lb://microservice-travel
          predicates:
            - Path=/api/**
          filters:
            - AuthFilter
        - id: microservice-uaa
          uri: lb://microservice-uaa
          predicates:
            - Path=/auth/**