server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8199/eureka/
  instance:
    hostname: localhost
    
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4445/user
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/api/**
        - id: microservice-travel
          uri: lb://microservice-travel
          predicates:
            - Path=/api/travel/**