server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8199/eureka/
  instance:
    hostname: localhost
    
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:4445/user
    
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeaderCookie
        - id: microservice-travel
          uri: lb://microservice-travel
          predicates:
            - Path=/api/travel/**
        - id: microservice-uaa
          uri: lb://microservice-uaa
          predicates:
            - Path=/user/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/movi-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/movi-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/movi-realm/protocol/openid-connect/token
        registration:
          movi-user-client:
            provider: keycloak
            client-id: movi-user-client
            client-secret: AenGOEwNJaPOlBlsWewQZRIKpKcJejGK
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/movi-user-client"