server:
  port: 8083
spring:
  profiles:
    active: dev, prod
  cloud:
    config:
      server:
        git:
          default-label: security
          uri: https://github.com/Zeitzn/travel-app-microservices  
          search-paths: config-data
          repos:
            development:
              pattern:
                - '*/dev'
              default-label: security
              uri: https://github.com/Zeitzn/travel-app-microservices
              search-paths: config-data
  application:
    name: microservice-config
    
  security:
   user:
     name: root
     password: s3cr3t